# Site settings
title: Our Beach Plum Wedding
email: tyler.magnin@gmail.com
description: "Kristina Gish & Tyler Magnin Wedding. June 25th, 2016."
baseurl: ""
url: "http://ourbeachplumwedding.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
